version: 2
 
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/phonics_app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run rspec
          command: docker-compose run web rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.5.3
    working_directory: ~/phonics_app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run rubocop
          command: docker-compose run web rubocop --require rubocop-airbnb
 
workflows:
  version: 2
  workflows:
    jobs:
      - rspec
      - rubocop